package io.github.hengxin.distributed_mobile_memo.pc.analysis.quantification;

/**
 * Quantifying executions generated by the RWN (R + W < N) protocol
 * for eventual consistency against atomicity.
 * Created by hengxin on 16-3-9.
 */
public class QuantifyingRWN {
}
